export type Observation = {time:number;recordedAt:string;retrievedAt:string;lat:number;lon:number;operator:string;vehicle:string;route:string;direction:string;journeyRef:string;destination:string;origin:string;aimedDeparture:string;sourceHash:string;sourceMember:string};
export type Journey = {id:string;operator:string;vehicle:string;route:string;direction:string;journeyRef:string;destination:string;origin:string;aimedDeparture:string;points:Observation[]};
export type Source = {url:string;sha256:string;bytes:number;capturedAt:string;retrievedAt:string};
export type Replay = {schemaVersion:number;mode:"archive";generatedAt:string;snapshotId?:string;start:number;end:number;frames:number[];bounds:number[];journeys:Journey[];sources:Source[];quality:{rawActivitiesInArea:number;uniqueObservations:number;duplicateObservations:number;conflictingObservations:number;outsideCaptureWindow:number;rejected:Record<string,number>;timetableMatched:boolean;scheduledCoverage:null};attribution:string;sourceUrl:string;limitations:string[]};
export type RoadMap = {attribution:string;sourceUrl:string;retrievedAt:string;roads:{name:string;kind:string;points:number[][]}[]};
export const cleanLabel = (s:string) => s.replaceAll('_',' ').trim();
export const clock = (t:number, seconds=false) => new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/London',hour:'2-digit',minute:'2-digit',...(seconds?{second:'2-digit'}:{})}).format(t);
export function lastObservation(journey:Journey,time:number){return journey.points.filter(p=>p.time<=time).at(-1);}
export function percentile(values:number[],fraction:number){if(!values.length)return null;const sorted=[...values].sort((a,b)=>a-b);return sorted[Math.min(sorted.length-1,Math.floor((sorted.length-1)*fraction))];}
export function gaps(journey:Journey){return journey.points.slice(1).map((p,i)=>(p.time-journey.points[i].time)/1000);}
export function routeKey(journey:Journey){return journey.operator+'|'+journey.route;}
export function latestVisible(journey:Journey,time:number,maxAge=120_000){const point=lastObservation(journey,time);return point&&time-point.time<=maxAge?point:undefined;}

import {z} from 'zod';
const pointSchema=z.object({time:z.number().finite(),recordedAt:z.string(),retrievedAt:z.string(),lat:z.number().min(-90).max(90),lon:z.number().min(-180).max(180),operator:z.string(),vehicle:z.string(),route:z.string(),direction:z.string(),journeyRef:z.string(),destination:z.string(),origin:z.string(),aimedDeparture:z.string(),sourceHash:z.string().regex(/^[a-f0-9]{64}$/),sourceMember:z.string()});
const journeySchema=z.object({id:z.string(),operator:z.string(),vehicle:z.string(),route:z.string(),direction:z.string(),journeyRef:z.string(),destination:z.string(),origin:z.string(),aimedDeparture:z.string(),points:z.array(pointSchema).min(1)});
const replaySchema=z.object({schemaVersion:z.literal(1),mode:z.literal('archive'),generatedAt:z.string(),snapshotId:z.string().optional(),start:z.number().finite(),end:z.number().finite(),frames:z.array(z.number().finite()).min(1),bounds:z.array(z.number()).length(4),journeys:z.array(journeySchema).min(1),sources:z.array(z.object({url:z.string().url().startsWith('https://data.datalibrary.uk/'),sha256:z.string().regex(/^[a-f0-9]{64}$/),bytes:z.number().nonnegative(),capturedAt:z.string(),retrievedAt:z.string()})).min(1),quality:z.object({rawActivitiesInArea:z.number(),uniqueObservations:z.number(),duplicateObservations:z.number(),conflictingObservations:z.number(),outsideCaptureWindow:z.number(),rejected:z.record(z.number()),timetableMatched:z.boolean(),scheduledCoverage:z.null()}),attribution:z.string(),sourceUrl:z.string().url().startsWith('https://data.datalibrary.uk/'),limitations:z.array(z.string())});
export function parseReplay(value:unknown):Replay{const data=replaySchema.parse(value);if(data.end<=data.start)throw Error('The recording has no valid replay window.');return data;}
export function parseRoadMap(value:unknown):RoadMap{return z.object({attribution:z.string(),sourceUrl:z.string(),retrievedAt:z.string(),roads:z.array(z.object({name:z.string(),kind:z.string(),points:z.array(z.array(z.number()).length(2))}))}).parse(value);}
export function visibleJourneys(journeys:Journey[],time:number){const vehicles=new Map<string,{journey:Journey;time:number}>();for(const journey of journeys){const point=latestVisible(journey,time);if(!point)continue;const key=journey.operator+'|'+journey.vehicle;const previous=vehicles.get(key);if(!previous||point.time>previous.time)vehicles.set(key,{journey,time:point.time});}return Array.from(vehicles.values()).map(v=>v.journey);}
